config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root 'articles#index'

  get '/news', to: 'articles#index'
  get '/news/:id', to: 'articles#show'
  get '/newcomments', to: 'comments#index'

  get '/submit', to: 'articles#new'
  post '/submit', to: 'articles#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'about#index'

  get '/v0/item/:id', to: 'items#show'
  post '/v0/item/create', to: 'items#create'

  resources :articles do
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class = "footer text-center">
  <%= link_to 'API', 'https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2', target: '_blank' %> |
  <%= link_to 'About', about_path %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar">
<ul class="nav">
  <li class="nav-item">
    <%= link_to image_tag("RMIT.png", border: 0, size: '15x15') %> RMIT News
  </li>
  <li class="nav-item">
    |
  </li>
  <li class="nav-item">
    <%= link_to 'Home', root_url, query: 'page' %>
  </li>
  <li class="nav-item">
    |
  </li>
  <li class="nav-item">
    <%= link_to 'Comments', newcomments_url %>
  </li>
  <li class="nav-item">
    |
  </li>
  <li class="nav-item">
    <%= link_to 'Submit', submit_url %>
  </li>
  <li class="nav-item">
    |
  </li>
  <% if !logged_in? %>
    <li class="nav-item">
      <!-- TODO: make this only show this if not already logged in -->
      <%= link_to 'Login', login_url %>
    </li>
  <% else %>
    <li class="nav-item">
      <!-- TODO: make this only show this if not already logged in -->
      <%= link_to 'Logout', logout_url, method: :delete %>
    </li>
  <% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>